<h1> Introduction to Tensorflow</h1>
<h1>______________________________________</h1>

<h3> What is a tensor?</h3>
<p>A tensor is a data that's passed between the operations. In effect, a Tensor is a multidimensional array. It can be zero dimensional, such as scalar value, one dimensional as line or vector, or 2 dimensional such as Matrix, and so on.</p>
<img src="table.png">

<h3>Data flow graph</h3>
<p>In a dataflow graph the nodes are called operations, which represent units of computation. The edges are tensors which represent the data consumed or produced by an operation.<br><br>
    In the diagram below, feature matrix is a <strong>placeholder.</strong> Placeholders can be sees as "holes" in your model, meaning "holes" through which you can pass the data from outside of the graph. Placeholders allow us to create our operations in the graph, without needing the data. When we want to execute the graph, we have to free the placeholders with our input data. This is why we need to <strong>initialize placeholders before using them</strong>. <br><br>
    In the diagram below, Weight matrix is a variable. Tensorflow variables, are used to share and persist some values, that are manipulated by the program. Also when we define a placeholder or a variable, Tensorflow adds an operation to your graph.
    <br> After all the operations we can create a session to run the graph, and perform the computations.
    <br>
    <img src = "dataflow.png">

<p> for example, the image below represents a graph in Tensorflow. <strong>W, x</strong> and <strong>b</strong> are tensors over the edge of this graph. <strong>MatMul</strong> is an operation over the tensors <strong>W, x,</strong>. After that <strong>Add</strong> is called to add the results of previous operator and <strong>b</strong>. The resultant tensors of each operations cross the next one until the end where it's possible to get the wanted result</p>
<img src = "nn.png">

<h2>Importing tensorflow</h2>

In [28]:
import tensorflow as tf

<h2> Building a graph</h2>
<p> Tensorflow works as a <strong><a href = "https://medium.com/tebs-lab/deep-neural-networks-as-computational-graphs-867fcaa56c9">graph computational model</a></strong>. 
    <br>
<p> To create our first graph we will use source operations, ones that do not need any information input. These source operations or "source ops" will pass their info to other operations which will execute computations.


In [29]:
a = tf.constant([2])
b = tf.constant([3])

<p>Now we will make an simple addition over the variables. The funciton <strong>tf.add()</strong> adds two elements (or simply you can do c = a + b.. but tf.add() looks cool though :-) </p>

In [30]:
c = tf.add(a,b)

<p> Now we will initialize a session to run our code. Sessions are a context for creating graph inside Tensorflow.</p>

In [31]:
session = tf.Session()

<p>Run the session to get the result</p>

In [32]:
result = session.run(c)
print(result)

[5]


<p>close the session to release the resources</p>


In [33]:
session.close()

<p>It's a drag to close the sessions all the time so <strong>with</strong> the help of <strong>with</strong> block(see what I did there :-) we can close the session automatically</p>

In [34]:
with tf.Session() as session:
    result = session.run(c)
    print(result)
    

[5]


<p>Now lets play around with the same objective but with tf.Graph().<br> We will create a graph, named graph1</p>

In [35]:
graph1 = tf.Graph()

<p>Now we can call the tensorflow functions that construct new tf.Operations and tf.Tensor objects and add them to the graph1, cause each <strong>tf.Operation is a node</strong> and each <strong>tf.Tensor is an edge in the graph.</strong>

<p>Lets add 2 constants to our graph. For example, calling tf.constant([2], name = 'constant_a') adds a single tf.Operation to the default graph. This operation produces the value 2, and returns a tf.Tensor that represents the value of the constant.<br>
Notice: tf.constant([2], name="constant_a") creates a new tf.Operation named "constant_a" and returns a tf.Tensor named "constant_a:0".</p>

In [36]:
with graph1.as_default():
    a = tf.constant([2], name = 'constant_a')
    b = tf.constant([3], name = 'constant_b')

In [37]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

<p>Lets make an operation over these tensors. 

In [38]:
with graph1.as_default():
    c = tf.add(a,b)

<p>Then we will initialize a session to run our code. Sessions are a context for creating a graph inside Tensorflow.</p>

In [39]:
sess = tf.Session(graph = graph1)

<p>Lets run the session</p>

In [40]:
res = sess.run(c)
print(res)
sess.close() # or just go with that with style :-)

[5]


<h2>Multidimensional arrays using Tensorflow</h2>

<p>Now lets start some simple yet cool stuff</p>

In [41]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([1,2,3])
    Matrix = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
    Tensor = tf.constant([[[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]]])

with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print("Scalar : %s" % result)
    result = sess.run(Vector)
    print("Vector: %s" % result)
    result = sess.run(Matrix)
    print("Matrix : %s" % result)
    result = sess.run(Tensor)
    print("Tensor : %s" % result)

Scalar : 2
Vector: [1 2 3]
Matrix : [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor : [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


In [42]:
print(Scalar.shape)
print(Vector.shape)
print(Matrix.shape)
print(Tensor.shape)

()
(3,)
(3, 3)
(3, 3, 3)


<p>Now lets play around with them</p>

In [43]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
    
    add_1_operation = tf.add(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one + Matrix_two
    
with tf.Session(graph = graph3) as sess:
    result = sess.run(add_1_operation)
    print("By using tf.add(): \n", result)
    result = sess.run(add_2_operation)
    print("By using '+': \n", result)
    

By using tf.add(): 
 [[3 4 5]
 [4 5 6]
 [5 6 7]]
By using '+': 
 [[3 4 5]
 [4 5 6]
 [5 6 7]]


<p>With the regular symbol definition and also the Tensorflow function we were able to get an element-wise multiplication, known as <b>Hadamard Product</b>.<br> <br>But for matrix multiplication? We have tf.matmul()

In [44]:
graph4 = tf.Graph()
with graph4.as_default():
    Matrix_one = tf.constant([[1,2],[3,4]])
    Matrix_two = tf.constant([[3,4],[5,6]])
    
    multi = tf.matmul(Matrix_one, Matrix_two)
    
with tf.Session(graph=graph4) as sess:
    result = sess.run(multi)
    print(result)

[[13 16]
 [29 36]]


<h2>Variables</h2>

<p><b>Why do we need variables?</b></p>
<p>TensorFlow variables are used to share and persistent some stats that are manipulated by our program. Means, when we define a variable, Tensorflow adds a tf.Operation to our graph. Then, this operation will store a writable tensor value that persists between tf.Session.run calls. So, you can update the value of a variable through each run, while you cannot update tensor(e.g a tensor created by tf.constant()) through multiple runs in a session.</p>

<br>
<b>How to define a variable?</b>
<p>Use the command <b>tf.Variable()<b>. To be able use variables in a computation graph it is necessary to initialize them before running the graph in a session, which is done by <b>tf.global_variables_initializer()</b>.

In [45]:
v = tf.Variable(20)

<p>Let's first create a simple counter, a variable that increases one unit at a time:</p>
<p>To do this we use the <b>tf.assign(reference_variable, value_to_update) command. tf.assign takes in two arguments, the <b>reference_variable</b> to update, and assign it to the <b>value_to_update</b> it by.

In [46]:
update = tf.assign(v, v+1)

<p>Variables must be initialized by running an initialization operation after having launched the graph. We first have add the initialization operation to the graph:</p>

In [47]:
init_op = tf.global_variables_initializer()

In [48]:
with tf.Session() as session:
    session.run(init_op)
    print(session.run(v))
    for _ in range(3):
        session.run(update)
        print(session.run(v))

20
21
22
23


<h2>Placeholders</h2>

<p>If we want to feed data to a Tensorflow graph from outside a graph, we are going to need to use placeholders.</p>
<br>
<b>What are placeholders?</b>
<p>Placeholders can be visualized as "holes" in your model, "holes" which allows to pass the data. We can create them using <b>tf.placeholder(datatype)</b>, where <b><i>datatype</i></b> specifies the type of data (int, float, str, bool) along with its precision(8,16,32,64) bits.</p>
<img src = "data.png">


<p>Create a placeholder</p>

In [49]:
a = tf.placeholder(tf.float32)

<p>Define a multiplication operation</p>

In [50]:
b = a *2

<p>Now we need to define and run the session, but since we created a "hole" in the model to pass the data, when we initialize the session we are obligated to pass an argument with the data, otherwise we'll get an error.</p>
<br>
<p>To pass the data into the model we call the session with an extra argument <b>feed_dict</b> in which we should pass a dictionary with each placeholder name followed by its data.</p>

In [51]:
with tf.Session() as sess:
    result = sess.run(b, feed_dict = {a:7})
    print(result)

14.0


<p>Since data in Tensorflow is passed in from of multidimensional arrays we can pass any kind of tensro through the placeholders to get the answer to the simple multiplication operation</p>

In [52]:
our_tensors ={a: [[[1,2,3],[4,5,6],[7,8,9],[10,11,12]] , [[13,14,15],[16,17,18],[19,20,21],[22,23,24]]]}

with tf.Session() as sess:
    result = sess.run(b, feed_dict = our_tensors)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


<h2>Operations</h2>
<p>These are the nodes that represent mathematical operations over the tensors in the graph, like add, subtract and multiply or even functions like activation functions.</p>
<br>
<p><b>tf.constant</b>, <b>tf.add</b>, <b>tf.matmul</b>, <b>tf.nn.sigmoid</b> are some operations(nodes) in Tensorflow. These are like function in python but operate directly over tensors and each does one specific thing</p>


In [55]:
graph5 = tf.Graph()
with graph5.as_default():
    a = tf.constant([5])
    b = tf.constant([2])
    sig = tf.placeholder(tf.float32)
    c = tf.add(a,b)
    d = tf.subtract(a,b)
    e = tf.nn.sigmoid(sig)

with tf.Session(graph = graph5) as sess:
    result = sess.run(c)
    print('c = %s' % result)
    result = sess.run(d)
    print('d = %s' % result)
    result = sess.run(e, feed_dict = {sig:1.5})
    print('e = %s' % result)

c = [7]
d = [3]
e = 0.81757444


<p>Thats the basics</p><h1>:-)</h1>
<h1>!!!WELCOME TO TENSORFLOW!!!</h1>